### PR TITLE
Remove extra validation set

### PR DESCRIPTION
**Pull request by TheooJ**
As discussed during the seminar yesterday, there was an extra validation set in the example :)

### CODE REVIEW

**Comment by juAlberge** [comment]
Hello, I've already fixed that in my code with some other changes! thanks

**Comment by Vincent-Maladiere** [comment]
Yeah, but it's not there yet, is it? So Theo's PR is valid, don't you think? The project is still in its early days but I think we should give people some room to contribute

**Review by Vincent-Maladiere — APPROVED** [review]
Thanks for contributing, @TheooJ! All feedback help :)

**Comment by Vincent-Maladiere** [comment]
You have a small error due to the number of samples in `X_train` not being even anymore

**Comment by TheooJ** [comment]
Just realized the features depended on the train shape -> bumping `test_size`

**Pull request merged**
